languageCode = "en-us"
theme = "awesome-identity"
title = "Su Nguyen's Identity"


## Profile Configurations
[params.profile]
  firstname = "Su"
  lastname = "T. Nguyen"
  title = "Senior Software Engineer"
  bio = """Hi, my name is Su. I'm a Senior Software Engineer with experience in software development.

  I currently work at [Nimble](https://nimblehq.co/) as a Senior Web Developer.

  Nice to meet you!
  """

[params.contacts]
  email = "vnntsu@gmail.com"
  github = "vnntsu"
  linkedin = "vnntsu"
